### ISSUE TITLE
Cache tests

### ISSUE THREAD

**Issue by slavingia** [anti-work/shortest#124] opened 2024-12-20 17:43 UTC
A way to make tests faster.

Via snapshot images? Via URLs?

Bounty: $1,000 for each PR that improves the speed of a shortest test.

**Comment by bojl** [comment] 2024-12-24 04:12
One of way of speeding up tests is to maintain a cache that maps the test input (prompt, site) to the steps the AI decides to take (mouse move, click, type, button press, etc). That way, during the next identical test run you can just have playwright execute the steps without calling the LLM until the test is complete (to verify that the test was successful). You might also be able to store jest verification steps along the way (like validating divs exist, etc) to avoid the need to call the LLM at all.

This is useful for testing regressions, but obviously not as useful when the page you're testing has changed since the last test run.

Another thing you can do is allow the LLM to suggest multiple action in a single prompt rather than 1 action = 1 prompt

**Comment by bojl** [comment] 2024-12-24 04:25
Ah I've been beaten to the punch, at least on the first suggestion-- https://github.com/anti-work/shortest/pull/134

**Comment by slavingia** [comment] 2024-12-24 10:36
Yep, that's probably the right approach. And rerun a step/whole test upon failure in case of a page change.

**Comment by gladyshcodes** [comment] 2024-12-26 12:38
@slavingia Hi there! That is what I have in mind and how I see caching implemented, what do you think?

Essentially, we could keep track of every step made by Playwright. We could call it action or similarly. Each action will be added to cache. On subsequent test runs, we would replay those instructions. If any of them fail, we will fallback to normal test execution and call LLM. I am also thinking of caching LLM responses. I am not sure about the performance gain and effectivity of such approach yet, just wanted to gather some feedback and thoughts :)

<img width="847" alt="Screenshot 2024-12-26 at 13 35 20" src="https://github.com/user-attachments/assets/2c906082-0059-4d82-827e-09ebf97e1809" />

**Comment by gladyshcodes** [comment] 2024-12-26 14:48
@slavingia Hi there! That is how I see caching implemented, what do you think?

Essentially, we could keep track of every step made along with LLM resps in cache. I believe it's better to do it per test rather than per test file. On initial run, each step will be stored in cache. On subsequent test runs, we would replay those instructions. If any of them fail or UI have changed, we will fall back to a normal test execution and call LLM, rebuilding cache on the fly. I am not sure about the performance gain and effectiveness of such approach yet, just wanted to gather some feedback and thoughts :)

<img width="1016" alt="Screenshot 2024-12-26 at 15 42 35" src="https://github.com/user-attachments/assets/ed6e929e-8bfe-4254-be46-76b44e86f4a3" />

**Comment by slavingia** [comment] 2024-12-26 15:20
Overall flow makes sense! Should make most tests very fast and computer use only needed in the case of failure, where certain things changed.

**Comment by gladyshcodes** [comment] 2024-12-26 17:57
I will make PR implementing those change soon 👍

**Comment by jonasanso** [comment] 2024-12-29 12:59
Hi there, I just started looking into shortest and found it really nice. Great job!!

Totally in favor of this issue / bounty. My main blocking points for using this at scale are speed and cost.

I have also seen @gladyshcodes PR 🙌 

A couple of ideas:
- Caching using the local file system is fine, taking into acocunt that most of the test executions will be part of a GitHub Action (or similar) the generated files can be cached using `actions/cache@v4` and resued across executions.
- There are pros and cons but, making the generated files part of the workflow could be interesting: 
  - It can help debug issues with the test 
  - It can make faster running the tests locally for a new tester joining the team
  - I understand it is not the main goal of this tool to help generate test code, but it could be an alternative way of using it
- Cache scope should be as small as possible to increase cache hits. I think per test is good for now, but there should be a way to divide a test into steps (login, create an entry) and cache the steps

**Comment by slavingia** [comment] 2024-12-29 13:27
We're working on chaining tests. That could act as the steps that can be cached individually.

Agree on caching via github workflow too.

**Comment by gladyshcodes** [comment] 2024-12-29 15:11
Thank you very much for your feedback @jonasanso

> but there should be a way to divide a test into steps (login, create an entry) and cache the steps

I think it’s important to eventually focus on normalizing each test by breaking it down into granular, manageable steps. For now, while we have chaining, tests can still group multiple actions into a single step

Agree, I think it's important to eventually focus on normalizing each test, breaking it down into granular, small steps to execute. For now, while we have chaining, tests can still group multiple actions into a single step

> Making the generated files part of the workflow could be interesting

Makes sense, @slavingia  do you think that should be done after #179?

**Comment by slavingia** [comment] 2024-12-29 15:24
Yep!

**Closed** 2024-12-30 19:58 UTC
Labels: priority
